apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-app
          image: crpi-m2no0xxy7uyli88r.cn-qingdao.personal.cr.aliyuncs.com/hitwh/account:1.0  # 替换为实际镜像地址
          ports:
            - containerPort: 8082  # 对应Spring Boot server.port
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: account-config
                  key: datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /account/index  # 使用服务端点进行就绪检查
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP  # 前端通过Ingress访问
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  datasource.url: "jdbc:mysql://mysql-service:3306/account_db?useSSL=false&characterEncoding=utf8"
  # 其他应用配置可在此添加
---
# 数据库密码应使用Secret（需单独创建）
# kubectl create secret generic db-secrets \
#   --from-literal=username=root \
#   --from-literal=password=yourpassword
