apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-app
          image: crpi-m2no0xxy7uyli88r.cn-qingdao.personal.cr.aliyuncs.com/hitwh/order:1.0
          ports:
            - containerPort: 8081  # 修改1: 容器端口改为8081
          env:
            - name: SERVER_PORT
              value: "8081"        # 修改2: 环境变量改为8081
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081            # 修改3: 健康检查端口改为8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /order/index    # 使用服务端点进行就绪检查
              port: 8081            # 修改4: 就绪检查端口改为8081
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081             # 修改5: 服务目标端口改为8081
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  datasource.url: "jdbc:mysql://mysql-service:3306/order_db?useSSL=false&characterEncoding=utf8"
